// eslint.config.js — a small, security-focused lint pass, not a style linter.
//
// Two plugins. eslint-plugin-no-unsanitized is the one that actually found something on its first
// run: dom.js's el() had a general-purpose `html` attribute doing a raw `node.innerHTML = v` with
// zero callers anywhere in the app — a live footgun waiting for whoever next needed to render a
// habit name or note with a bit of formatting, at which point it would have become a real stored-XSS
// path (anyone holding a room's code can push arbitrary payload text into the shared log — see
// security/README.md). Removed rather than sanitized, since nothing used it. The one legitimate
// innerHTML assignment left (js/ui/levelmark.js, building an SVG from numbers only) is annotated
// with why it's safe rather than silenced by config, so the reasoning travels with the code.
//
// eslint-plugin-security adds the rest of the usual suspects (non-literal fs paths, unsafe
// child_process use, etc.) — most don't apply to a browser app with no dependencies, but they're
// cheap insurance against code that gets added later and does. detect-object-injection is turned
// off below: on this codebase it flags ~140 ordinary `obj[key]` reads against internal Maps/objects
// with no user-controlled key anywhere near them, which is noise, not signal — see the rule's own
// docs on why it can't tell the two apart. A screen full of warnings nobody reads is worse than no
// scan at all.

import globals from "globals";
import security from "eslint-plugin-security";
import noUnsanitized from "eslint-plugin-no-unsanitized";

export default [
  {
    ignores: [
      "node_modules/**", "test-results/**", "playwright-report/**", "dist/**",
      "service-worker.js", // generated by scripts/gen-sw-shell.mjs — lint the generator, not its output
    ],
  },
  security.configs.recommended,
  noUnsanitized.configs.recommended,
  { rules: { "security/detect-object-injection": "off" } },
  {
    // The app itself: browser-only, no Node globals, ES modules.
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.browser },
    },
  },
  {
    // Everything that runs under Node: the dev server, build/gen scripts, the two test suites,
    // and the write-side pentest tooling.
    files: ["scripts/**/*.mjs", "test/**/*.mjs", "e2e/**/*.mjs", "security/**/*.mjs", "*.config.mjs", "eslint.config.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
  {
    // scripts/ is dev-only tooling (a local dev server, build/gen scripts) that never touches
    // network input or a secret: dev-server.mjs already contains its own path (target.startsWith
    // (root)) before any fs call; gen-sw-shell.mjs only ever reads paths derived from the project's
    // own source files. Both trip detect-non-literal-fs-filename structurally (a variable reaches
    // an fs call) with nothing unsafe behind it. perf-levels.mjs's flagged "timing attack" is a
    // JSON.stringify(...) === JSON.stringify(...) determinism check against the perf probe's own
    // output, not a secret comparison.
    files: ["scripts/**/*.mjs"],
    rules: {
      "security/detect-non-literal-fs-filename": "off",
      "security/detect-possible-timing-attacks": "off",
    },
  },
];
